version: '3'
name: gpressfeed
services:
#  tunnel:
#    container_name: cloudflaredtunnel
#    image: cloudflare/cloudflared:latest
#    command: tunnel run --token <<cloudflareToken>>
#    networks:
#      - client-side 
  reverse-proxy:
    container_name: reverseproxy
    build: ./ReverseProxy
    ports:
     - "80:80"
    networks:
      - client-side
    depends_on:
      - ui
      - api
  ui:
    container_name: gpressfeedui
    build: ./GPressFeed.UI
    networks:
      - client-side
    depends_on:
      - api
  api:
    container_name: gpressfeedapi
    build: ./GPressFeed.API
    networks:
      - client-side
      - server-side
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<<dbpassword>>
      - POSTGRES_DB=gpressfeed
#    ports:
#      - "5432:5432"
    networks:
      - server-side
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

networks:
  client-side: {}
  server-side: {}